on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

name: build-ui
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Setup GCC
      uses: Dup4/actions-setup-gcc@v1
      with:
        version: latest
    - name: Checkout Repository
      uses: actions/checkout@main
    - name: Build
      run: make build-ui